/* eslint-disable max-len */
export const ITEMICONURL = 'http://ddragon.leagueoflegends.com/cdn/12.6.1/img/item/';
export const CHAMPIONICONURL = 'https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-icons/';
export const RUNEICONURL = 'https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/';

export const championIds = {
  266: 'Aatrox',
  103: 'Ahri',
  84: 'Akali',
  166: 'Akshan',
  12: 'Alistar',
  32: 'Amumu',
  34: 'Anivia',
  1: 'Annie',
  523: 'Aphelios',
  22: 'Ashe',
  136: 'AurelionSol',
  268: 'Azir',
  432: 'Bard',
  53: 'Blitzcrank',
  63: 'Brand',
  201: 'Braum',
  51: 'Caitlyn',
  164: 'Camille',
  69: 'Cassiopeia',
  31: 'Chogath',
  42: 'Corki',
  122: 'Darius',
  131: 'Diana',
  119: 'Draven',
  36: 'DrMundo',
  245: 'Ekko',
  60: 'Elise',
  28: 'Evelynn',
  81: 'Ezreal',
  9: 'Fiddlesticks',
  114: 'Fiora',
  105: 'Fizz',
  3: 'Galio',
  41: 'Gangplank',
  86: 'Garen',
  150: 'Gnar',
  79: 'Gragas',
  104: 'Graves',
  887: 'Gwen',
  120: 'Hecarim',
  74: 'Heimerdinger',
  420: 'Illaoi',
  39: 'Irelia',
  427: 'Ivern',
  40: 'Janna',
  59: 'JarvanIV',
  24: 'Jax',
  126: 'Jayce',
  202: 'Jhin',
  222: 'Jinx',
  145: 'Kaisa',
  429: 'Kalista',
  43: 'Karma',
  30: 'Karthus',
  38: 'Kassadin',
  55: 'Katarina',
  10: 'Kayle',
  141: 'Kayn',
  85: 'Kennen',
  121: 'Khazix',
  203: 'Kindred',
  240: 'Kled',
  96: 'KogMaw',
  7: 'Leblanc',
  64: 'LeeSin',
  89: 'Leona',
  876: 'Lillia',
  127: 'Lissandra',
  236: 'Lucian',
  117: 'Lulu',
  99: 'Lux',
  54: 'Malphite',
  90: 'Malzahar',
  57: 'Maokai',
  11: 'MasterYi',
  21: 'MissFortune',
  62: 'MonkeyKing',
  82: 'Mordekaiser',
  25: 'Morgana',
  267: 'Nami',
  75: 'Nasus',
  111: 'Nautilus',
  518: 'Neeko',
  76: 'Nidalee',
  56: 'Nocturne',
  20: 'Nunu',
  2: 'Olaf',
  61: 'Orianna',
  516: 'Ornn',
  80: 'Pantheon',
  78: 'Poppy',
  555: 'Pyke',
  246: 'Qiyana',
  133: 'Quinn',
  497: 'Rakan',
  33: 'Rammus',
  421: 'RekSai',
  526: 'Rell',
  888: 'Renata',
  58: 'Renekton',
  107: 'Rengar',
  92: 'Riven',
  68: 'Rumble',
  13: 'Ryze',
  360: 'Samira',
  113: 'Sejuani',
  235: 'Senna',
  147: 'Seraphine',
  875: 'Sett',
  35: 'Shaco',
  98: 'Shen',
  102: 'Shyvana',
  27: 'Singed',
  14: 'Sion',
  15: 'Sivir',
  72: 'Skarner',
  37: 'Sona',
  16: 'Soraka',
  50: 'Swain',
  517: 'Sylas',
  134: 'Syndra',
  223: 'TahmKench',
  163: 'Taliyah',
  91: 'Talon',
  44: 'Taric',
  17: 'Teemo',
  412: 'Thresh',
  18: 'Tristana',
  48: 'Trundle',
  23: 'Tryndamere',
  4: 'TwistedFate',
  29: 'Twitch',
  77: 'Udyr',
  6: 'Urgot',
  110: 'Varus',
  67: 'Vayne',
  45: 'Veigar',
  161: 'Velkoz',
  711: 'Vex',
  254: 'Vi',
  234: 'Viego',
  112: 'Viktor',
  8: 'Vladimir',
  106: 'Volibear',
  19: 'Warwick',
  498: 'Xayah',
  101: 'Xerath',
  5: 'XinZhao',
  157: 'Yasuo',
  777: 'Yone',
  83: 'Yorick',
  350: 'Yuumi',
  154: 'Zac',
  238: 'Zed',
  221: 'Zeri',
  115: 'Ziggs',
  26: 'Zilean',
  142: 'Zoe',
  143: 'Zyra',
};

export const romanNumbers = {
  I: 1,
  II: 2,
  III: 3,
  IV: 4,
  V: 5,
};

export const queueIds = {
  0: '',
  2: 'Blind Pick',
  4: 'Ranked Solo',
  6: 'Ranked Premade',
  7: 'Co-op vs AI',
  8: '3v3 Normal',
  9: '3v3 Ranked Flex',
  14: 'Draft Pick',
  16: 'Dominion Blind Pick',
  17: 'Dominion Draft Pick',
  25: 'Dominion Co-op vs AI',
  31: 'Co-op vs AI Intro Bot',
  32: 'Co-op vs AI Beginner Bot',
  33: 'Co-op vs AI Intermediate Bot',
  41: '3v3 Ranked Team',
  42: 'Ranked Team',
  52: 'Co-op vs AI',
  61: 'Team Builder',
  65: 'ARAM',
  67: 'ARAM Co-op vs AI',
  70: 'One for All',
  72: '1v1 Snowdown Showdown',
  73: '2v2 Snowdown Showdown',
  75: '6v6 Hexakill',
  76: 'Ultra Rapid Fire',
  78: 'One For All: Mirror Mode',
  83: 'Co-op vs AI Ultra Rapid Fire',
  91: 'Doom Bots Rank 1',
  92: 'Doom Bots Rank 2',
  93: 'Doom Bots Rank 5',
  96: 'Ascension',
  98: '6v6 Hexakill',
  100: 'ARAM',
  300: 'Legend of the Poro King',
  310: 'Nemesis',
  313: 'Black Market Brawlers',
  315: 'Nexus Siege',
  317: 'Definitely Not Dominion',
  318: 'ARURF',
  325: 'All Random',
  400: 'Draft Pick',
  410: 'Ranked Dynamic',
  420: 'Ranked Solo',
  430: 'Blind Pick',
  440: 'Ranked Flex',
  450: 'ARAM',
  460: '3v3 Blind Pick',
  470: '3v3 Ranked Flex',
  600: 'Blood Hunt Assassin',
  610: 'Dark Star: Singularity',
  700: 'Clash',
  800: 'Co-op vs. AI Intermediate Bot',
  810: 'Co-op vs. AI Intro Bot',
  820: 'Co-op vs. AI Beginner Bot',
  830: 'Co-op vs. AI Intro Bot',
  840: 'Co-op vs. AI Beginner Bot',
  850: 'Co-op vs. AI Intermediate Bot',
  900: 'ARURF',
  910: 'Ascension',
  920: 'Legend of the Poro King',
  940: 'Nexus Siege',
  950: 'Doom Bots Voting',
  960: 'Doom Bots Standard',
  980: 'Star Guardian Invasion: Normal',
  990: 'Star Guardian Invasion: Onslaught',
  1000: 'PROJECT: Hunters',
  1010: 'Snow ARURF',
  1020: 'One for All',
  1030: 'Odyssey Extraction: Intro',
  1040: 'Odyssey Extraction: Cadet',
  1050: 'Odyssey Extraction: Crewmember',
  1060: 'Odyssey Extraction: Captain',
  1070: 'Odyssey Extraction: Onslaught',
  1090: 'Teamfight Tactics',
  1100: 'Ranked Teamfight Tactics',
  1110: 'Teamfight Tactics Tutorial',
  1111: 'Teamfight Tactics test',
  1200: 'Nexus Blitz',
  1300: 'Nexus Blitz',
  1400: 'Ultimate Spellbook',
  1900: 'Pick URF',
  2000: 'Tutorial 1',
  2010: 'Tutorial 2',
  2020: 'Tutorial 3',
};

export const summonerSpells = {
  1: 'Cleanse',
  3: 'Exhaust',
  4: 'Flash',
  6: 'Ghost',
  7: 'Heal',
  11: 'Smite',
  12: 'Teleport',
  13: 'Clarity',
  14: 'Ignite',
  21: 'Barrier',
  30: 'PoroKing Recall',
  31: 'Poro Toss',
  32: 'Mark',
  39: 'Mark',
};

export const runeIcons = {
  8100: 'perk-images/styles/7200_domination.png',
  8112: 'perk-images/styles/domination/electrocute/electrocute.png',
  8124: 'perk-images/styles/domination/predator/predator.png',
  8128: 'perk-images/styles/domination/darkharvest/darkharvest.png',
  9923: 'perk-images/styles/domination/hailofblades/hailofblades.png',
  8126: 'perk-images/styles/domination/cheapshot/cheapshot.png',
  8139: 'perk-images/styles/domination/tasteofblood/greenterror_tasteofblood.png',
  8143: 'perk-images/styles/domination/suddenimpact/suddenimpact.png',
  8136: 'perk-images/styles/domination/zombieward/zombieward.png',
  8120: 'perk-images/styles/domination/ghostporo/ghostporo.png',
  8138: 'perk-images/styles/domination/eyeballcollection/eyeballcollection.png',
  8135: 'perk-images/styles/domination/treasurehunter/treasurehunter.png',
  8134: 'perk-images/styles/domination/ingenioushunter/ingenioushunter.png',
  8105: 'perk-images/styles/domination/relentlesshunter/relentlesshunter.png',
  8106: 'perk-images/styles/domination/ultimatehunter/ultimatehunter.png',
  8300: 'perk-images/styles/7203_whimsy.png',
  8351: 'perk-images/styles/inspiration/glacialaugment/glacialaugment.png',
  8360: 'perk-images/styles/inspiration/unsealedspellbook/unsealedspellbook.png',
  8369: 'perk-images/styles/inspiration/firststrike/firststrike.png',
  8306: 'perk-images/styles/inspiration/hextechflashtraption/hextechflashtraption.png',
  8304: 'perk-images/styles/inspiration/magicalfootwear/magicalfootwear.png',
  8313: 'perk-images/styles/inspiration/perfecttiming/perfecttiming.png',
  8321: 'perk-images/styles/inspiration/futuresmarket/futuresmarket.png',
  8316: 'perk-images/styles/inspiration/miniondematerializer/miniondematerializer.png',
  8345: 'perk-images/styles/inspiration/biscuitdelivery/biscuitdelivery.png',
  8347: 'perk-images/styles/inspiration/cosmicinsight/cosmicinsight.png',
  8410: 'perk-images/styles/resolve/approachvelocity/approachvelocity.png',
  8352: 'perk-images/styles/inspiration/timewarptonic/timewarptonic.png',
  8000: 'perk-images/styles/7201_precision.png',
  8005: 'perk-images/styles/precision/presstheattack/presstheattack.png',
  8008: 'perk-images/styles/precision/lethaltempo/lethaltempotemp.png',
  8021: 'perk-images/styles/precision/fleetfootwork/fleetfootwork.png',
  8010: 'perk-images/styles/precision/conqueror/conqueror.png',
  9101: 'perk-images/styles/precision/overheal.png',
  9111: 'perk-images/styles/precision/triumph.png',
  8009: 'perk-images/styles/precision/presenceofmind/presenceofmind.png',
  9104: 'perk-images/styles/precision/legendalacrity/legendalacrity.png',
  9105: 'perk-images/styles/precision/legendtenacity/legendtenacity.png',
  9103: 'perk-images/styles/precision/legendbloodline/legendbloodline.png',
  8014: 'perk-images/styles/precision/coupdegrace/coupdegrace.png',
  8017: 'perk-images/styles/precision/cutdown/cutdown.png',
  8299: 'perk-images/styles/sorcery/laststand/laststand.png',
  8400: 'perk-images/styles/7204_resolve.png',
  8437: 'perk-images/styles/resolve/graspoftheundying/graspoftheundying.png',
  8439: 'perk-images/styles/resolve/veteranaftershock/veteranaftershock.png',
  8465: 'perk-images/styles/resolve/guardian/guardian.png',
  8446: 'perk-images/styles/resolve/demolish/demolish.png',
  8463: 'perk-images/styles/resolve/fontoflife/fontoflife.png',
  8401: 'perk-images/styles/resolve/mirrorshell/mirrorshell.png',
  8429: 'perk-images/styles/resolve/conditioning/conditioning.png',
  8444: 'perk-images/styles/resolve/secondwind/secondwind.png',
  8473: 'perk-images/styles/resolve/boneplating/boneplating.png',
  8451: 'perk-images/styles/resolve/overgrowth/overgrowth.png',
  8453: 'perk-images/styles/resolve/revitalize/revitalize.png',
  8242: 'perk-images/styles/sorcery/unflinching/unflinching.png',
  8200: 'perk-images/styles/7202_sorcery.png',
  8214: 'perk-images/styles/sorcery/summonaery/summonaery.png',
  8229: 'perk-images/styles/sorcery/arcanecomet/arcanecomet.png',
  8230: 'perk-images/styles/sorcery/phaserush/phaserush.png',
  8224: 'perk-images/styles/sorcery/nullifyingorb/pokeshield.png',
  8226: 'perk-images/styles/sorcery/manaflowband/manaflowband.png',
  8275: 'perk-images/styles/sorcery/nimbuscloak/6361.png',
  8210: 'perk-images/styles/sorcery/transcendence/transcendence.png',
  8234: 'perk-images/styles/sorcery/celerity/celeritytemp.png',
  8233: 'perk-images/styles/sorcery/absolutefocus/absolutefocus.png',
  8237: 'perk-images/styles/sorcery/scorch/scorch.png',
  8232: 'perk-images/styles/sorcery/waterwalking/waterwalking.png',
  8236: 'perk-images/styles/sorcery/gatheringstorm/gatheringstorm.png',
};
